[build-system]
requires = ["setuptools", "wheel", "numpy"]
build-backend = "setuptools.build_meta"

[tool.coverage.run]
omit = [
    # omit anything from the test directory and subdirectories
    "test/*",
]